daily_status/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('status.urls')),
    path('admin/', admin.site.urls),
]

status/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:id>", views.index, name="index"),
    path("member", views.set_member, name="set_member"),
    path("add", views.add_status, name="add_status"),
    path("edit/<int:id>", views.edit_status, name="edit_status"),
    path("delete/<int:id>", views.delete_status, name="delete_status"),
    path("member/delete/<int:id>", views.delete_member, name="delete_member"),
    path("member/offline", views.add_offline_member, name="add_offline_member"),
    path("member/offline/delete/<int:id>", views.delete_offline_member, name="delete_offline_member"),
    path("email/browser", views.create_email_within_browser, name="create_email_within_browser"),
    path("email/outlook", views.create_email_in_outlook, name="create_email_in_outlook"),
]

status/models.py
from django.db import models

# Create your models here.


class Role(models.IntegerChoices):
    developer = 1
    tester = 2


class AbstractMember(models.Model):
    name = models.CharField(max_length=100, unique=True)
    role = models.IntegerField(choices=Role.choices)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Member(AbstractMember):
    class Meta:
        verbose_name = 'Member'
        verbose_name_plural = 'Members'

    def __str__(self):
        return self.name


class OfflineMember(AbstractMember):

    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "offlinemember"
        verbose_name_plural = "offlinemembers"

    def __str__(self):
        return self.name


class Status(models.Model):

    incident = models.CharField(max_length=100, blank=True)
    description = models.TextField()
    severity = models.CharField(max_length=50, blank=True)
    progress = models.CharField(max_length=200, blank=True)
    comment = models.TextField(blank=True)
    member = models.ForeignKey("Member", on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Status'
        verbose_name_plural = 'Status'

status/forms.py
from django.forms import ModelForm, ChoiceField
from .models import Member, OfflineMember, Status


class MemberForm(ModelForm):
    # role = ChoiceField(choices=Role.choices, required=True)
    class Meta:
        model = Member
        fields = ("name", "role")


class OfflineMemberForm(ModelForm):

    class Meta:
        model = OfflineMember
        fields = ("name", "role")


class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ("incident", "description", "severity", "progress", "comment")

status/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.template import loader
from django.utils import timezone
from django.views.decorators.http import require_GET, require_POST
import json
import win32com.client as win32
import pythoncom
from yaml import load, FullLoader
from .models import Member, OfflineMember, Status
from .forms import MemberForm, OfflineMemberForm, StatusForm
# Create your views here.


def index(request, id=None):
    """Index view. Renders the main page. It'll given Member form, status form and status of the
    Member. The Member form is used to set the Member/tester name.
    """
    context = {
        'status_form': StatusForm()
    }
    if request.session.get('member'):
        try:
            member = Member.objects.get(
                name=request.session['member'])
            context['member_form'] = MemberForm(instance=member)
            status = Status.objects.filter(
                member=member, created_date__date=timezone.now().date())
            context['status'] = status
        except Member.DoesNotExist:
            context['member_form'] = MemberForm()
        if id is not None:
            try:
                status = Status.objects.get(pk=id)
                edit_status_form = StatusForm(instance=status)
                context['status_form'] = edit_status_form
                context['is_status_being_edited'] = True
                context['edit_status_id'] = status.id
            except Status.DoesNotExist:
                messages.warning(
                    request, 'Status with id {0} does not exist'.format(id))
    else:
        context['member_form'] = MemberForm()
        messages.info(request, 'Please set member details first.')
    context['offline_members'] = OfflineMember.objects.filter(
        created_date__date=timezone.now().date())
    context['offline_members_form'] = OfflineMemberForm()
    return render(request, 'status/index.html', context)


@require_POST
def set_member(request):
    """
    view to set Member name in database and in session. If duplicate is found then view will update the member and redirect.
    """
    member_form = MemberForm(request.POST)
    if member_form.is_valid():
        new_member = member_form.save()
        messages.success(
            request, '{0} set successfully.'.format(new_member.name))
        request.session['member'] = new_member.name
    else:
        if member_form.has_error('name', 'unique'):
            try:
                member = Member.objects.get(name=request.POST['name'])
                member_form = MemberForm(request.POST, instance=member)
                if member_form.is_valid():
                    member = member_form.save()
                    messages.success(
                        request, '{0} set successfully.'.format(member.name))
                    request.session['member'] = member.name
                else:
                    messages.error(request, 'Error updating member')
                    messages.error(request, member_form.errors)
            except Member.DoesNotExist:
                messages.error(
                    request, 'Something went wrong. Duplicate name exists but unable to fetch it. Contact developer.')
        else:
            messages.error(request, member_form.errors)

    return redirect('index')


@require_POST
def add_status(request):
    """
    Add Status
    """
    if request.session.get('member'):
        status_form = StatusForm(request.POST)
        if status_form.is_valid():
            status = status_form.save(commit=False)
            status.member = get_object_or_404(
                Member, name=request.session.get('member'))
            status.save()
            messages.success(request, 'Status added successfully.')
        else:
            messages.error(request, status_form.errors)
    else:
        messages.error(request, 'Please set member details first.')
    return redirect('index')


@require_POST
def edit_status(request, id):
    """
    Edit a status based on Id
    """
    try:
        status = Status.objects.get(pk=id)
        edit_status_form = StatusForm(request.POST, instance=status)
        if edit_status_form.is_valid():
            edit_status_form.save()
            messages.success(request, 'Status updated successfully.')
        else:
            messages.error(request, edit_status_form.errors)
    except Status.DoesNotExist:
        messages.warning(
            request, 'Status with id {0} does not exist'.format(id))
    return redirect('index')


@require_GET
def delete_status(request, id):
    """
    Delete a status based on the given id
    """
    try:
        status = Status.objects.get(pk=id)
        status.delete()
        messages.success(
            request, 'Status with id {0} deleted successfully.'.format(id))
    except Status.DoesNotExist:
        messages.warning(
            request, "Status with id {0} doesn't exist".format(id))
    return redirect('index')


@require_GET
def delete_member(request, id):
    """
    Delete member based on Id
    """
    try:
        member = Member.objects.get(pk=id)
        member.delete()
        request.session.flush()
        messages.success(
            request, 'Member with name {0} deleted successfully. Now please try to set member details again.'.format(member.name))
    except Member.DoesNotExist:
        messages.warning(
            request, "Member with id {0} doesn't exist".format(id))
    return redirect('index')


def create_email_within_browser(request):
    """
    Create email with all the members status for present day and display it in browser
    """
    try:
        status = Status.objects.filter(
            created_date__date=timezone.now().date()).order_by('member__name')
        offline_members = OfflineMember.objects.filter(
            created_date__date=timezone.now().date())
        if not status.exists() and not offline_members.exists():
            messages.warning(request, 'No status set for today')
            return redirect('index')
        context = {
            'status': status,
            'offline_members': offline_members
        }
    except Status.DoesNotExist:
        messages.warning(request, 'No status found for today')
        return redirect('index')
    return render(request, 'status/email.html', context)


def create_email_in_outlook(request):
    """
    Generate email and open it in outlook. Beware this view must be called on host machine only.
    """
    status = Status.objects.filter(
        created_date__date=timezone.now().date()).order_by('member__name')
    offline_members = OfflineMember.objects.filter(
        created_date__date=timezone.now().date())
    context = {
        'status': status,
        'offline_members': offline_members
    }
    email_body = loader.render_to_string('status/email.html', context, request)
    with open('mailing_list.yml') as f:
        try:
            mailing_list = load(f, FullLoader)
            print(';'.join(mailing_list['to']))
            pythoncom.CoInitialize()
            outlook = win32.Dispatch('outlook.application')
            mail = outlook.CreateItem(0)
            mail.To = ';'.join(mailing_list['to'])
            mail.CC = ';'.join(mailing_list['cc'])
            mail.Subject = 'Offshore status {0}'.format(
                timezone.localdate().strftime('%m/%d/%Y'))
            mail.HtmlBody = email_body
            mail.Display(False)
        except NameError as error:
            messages.error(request, error)
    return redirect('index')


@require_POST
def add_offline_member(request):
    """
    Add members who are offline for the day
    """
    offline_member_form = OfflineMemberForm(request.POST)
    if offline_member_form.is_valid():
        offline_member = offline_member_form.save()
        messages.success(
            request, '{0} added to offline members for today.'.format(offline_member.name))
    else:
        messages.error(request, offline_member_form.errors)
    return redirect('index')


@require_GET
def delete_offline_member(request, id):
    """
    Delete offline members based on id
    """
    offline_member = get_object_or_404(
        OfflineMember, pk=id, created_date__date=timezone.now().date())
    offline_member.delete()
    messages.success(
        request, 'Member with name {0} deleted successfully from offline members list.'.format(offline_member.name))
    return redirect('index')

status/templates/status/email.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email</title>
    <style>
        /* Remove space around the email design. */
        html,
        body {
            margin: 0 auto !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
            font-family: Calibri, sans-serif
        }

        /* Stop Outlook resizing small text. */
        * {
            -ms-text-size-adjust: 100%;
        }

        /* Stop Outlook from adding extra spacing to tables. */
        table,
        td {
            mso-table-lspace: 0pt !important;
            mso-table-rspace: 0pt !important;
        }

        /* Use a better rendering method when resizing images in Outlook IE. */
        img {
            -ms-interpolation-mode: bicubic;
        }

        {% comment %} table {
            width: 75%;
            margin-left: 2em;
        } {% endcomment %}

        thead {
            background-color: #ff8045;
        }

        table,
        th,
        td {
            text-align: center;
            vertical-align: middle;
            border: 1px solid #000000;
            border-collapse: collapse;
            padding: 0.5rem;
        }

        .status-heading {
            text-decoration: underline;
        }
    </style>
</head>

<body width="100%" style="margin: 0; padding: 0 !important; mso-line-height-rule: exactly;">
    
    <p>
        Hello Kristine/Gopal,
    </p>
    <p>
        Below is the Status of Offshore Development &amp; Testing team for today.
    </p>
    {% regroup status by member as status_by_member %}
    {% comment %} Developer's status {% endcomment %}
    <p class="status-heading">
        <strong>Developer's Status</strong>
    </p>
    <table role="presentation" cellspacing="0" cellpadding="0" border="0">
        <thead>
            <tr>
                <th>Developer</th>
                <th>Incident/Problem Code</th>
                <th>Description</th>
                <th>Severity</th>
                <th>Progress</th>
                <th>Comments</th>
            </tr>
        </thead>
        <tbody>
            {% for member, status in status_by_member %}
            {% if member.role == 1 %}
            {% for s in status %}
            <tr>
                {% if forloop.first %}
                <td rowspan="{{ status|length }}">
                    {{ member.name }}
                </td>
                {% endif %}
                <td>
                    {{ s.incident }}
                </td>
                <td>
                    {{ s.description }}
                </td>
                <td>
                    {{ s.severity }}
                </td>
                <td>
                    {{ s.progress }}
                </td>
                <td>
                    {{ s.comment }}
                </td>
            </tr>
            {% endfor %}
            {% endif %}
            {% endfor %}
            {% comment %} Add offline developer's to table {% endcomment %}
            {% for member in offline_members %}
            {% if member.role == 1 %}
            <tr>
                <td>{{ member.name }}</td>
                <td colspan="5">OOO</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% comment %} Tester's status {% endcomment %}
    <p class="status-heading">
        <strong>Tester's Status</strong>
    </p>
    <table role="presentation" cellspacing="0" cellpadding="0" border="0">
        <thead>
            <tr>
                <th>Tester</th>
                <th>Incident/Problem Code</th>
                <th>Description</th>
                <th>Severity</th>
                <th>Progress</th>
                <th>Comments</th>
            </tr>
        </thead>
        <tbody>
            {% for member, status in status_by_member %}
            {% if member.role == 2 %}
            {% for s in status %}
            <tr>
                {% if forloop.first %}
                <td rowspan="{{ status|length }}">
                    {{ member.name }}
                </td>
                {% endif %}
                <td>
                    {{ s.incident }}
                </td>
                <td>
                    {{ s.description }}
                </td>
                <td>
                    {{ s.severity }}
                </td>
                <td>
                    {{ s.progress }}
                </td>
                <td>
                    {{ s.comment }}
                </td>
            </tr>
            {% endfor %}
            {% endif %}
            {% endfor %}
        {% comment %} Add offline tester's to table {% endcomment %}
            {% for member in offline_members %}
            {% if member.role == 2 %}
            <tr>
                <td>{{ member.name }}</td>
                <td colspan="5">OOO</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</body>

</html>

status/templates/status/index.html
{% extends 'baseTemplate.html' %}
{% load widget_tweaks %}
{% block title %}
Daily Status
{% endblock title %}
{% block content %}
{% comment %} Member form section {% endcomment %}
<section class="section" id="set-member">
    <div class="box">
        <h1 class="title has-text-centered">Set Member details</h1>
        {% comment %} Form to set Member name {% endcomment %}
        <form method="POST" action="{% url 'set_member' %}" class="ml-6">
            {% csrf_token %}
            <div class="columns is-centered">
                <div class="column is-one-third is-offset-2">
                    <div class="field is-horizontal">
                        {% comment %} Member Field {% endcomment %}
                        <div class="field-label is-normal">
                            <label for="{{ member_form.name.id_for_label }}" class="label">Developer/Tester Name</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    {% render_field member_form.name class="input is-primary" placeholder=member_form.name.label value=request.session.member %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="field is-horizontal">
                        {% comment %} Role Field {% endcomment %}
                        <div class="field-label is-normal">
                            <label for="{{ member_form.role.id_for_label }}" class="label">Role</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <div class="select is-primary">
                                        {{ member_form.role }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <!-- Left empty for spacing -->
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <input type="submit" value="Set" class="button is-primary is-outlined">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% comment %} Quick links {% endcomment %}
        <div class="columns is-centered">
            <div class="column is-1">
                <a class="tag is-link is-light" href="#status-section">Status</a>
            </div>
            <div class="column is-1">
                <a class="tag is-link is-light" href="#status-form">Add status</a>
            </div>
            <div class="column is-2">
                <a class="tag is-link is-light" href="#offline-member-section">Add offline member</a>
            </div>
        </div>
    </div>
</section>
{% comment %} Status table section {% endcomment %}
<section class="section" id="status-section">
    <div class="box">
        <!-- Render status -->
        <h1 class="title has-text-centered">Status</h1>
        <div class="table-container">
            <table class="table is-hoverable is-striped is-fullwidth">
                <thead>
                    <tr>
                        <th>
                            Incident
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Severity
                        </th>
                        <th>
                            Progress
                        </th>
                        <th>
                            Comment
                        </th>
                        <th>
                            Edit
                        </th>
                        <th>
                            Delete
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for s in status %}
                    <tr>
                        <td>
                            {{ s.incident }}
                        </td>
                        <td>
                            {{ s.description }}
                        </td>
                        <td>
                            {{ s.severity }}
                        </td>
                        <td>
                            {{ s.progress }}
                        </td>
                        <td>
                            {{ s.comment }}
                        </td>
                        <td>
                            <a href="{% url 'index' id=s.id%}#status-form">Edit</a>
                        </td>
                        <td>
                            <a href="{% url 'delete_status' s.id%}">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% comment %} Add staus form section {% endcomment %}
<section class="section" id="status-form">
    <div class="box">
        <h1 class="title has-text-centered">Add Status</h1>
        <form
            action="{% if is_status_being_edited %}{% url 'edit_status' edit_status_id %}{% else %}{% url 'add_status' %}{% endif %}"
            method="POST">
            {% csrf_token %}
            {% for field in status_form %}
            <div class="field is-horizontal">
                <div class="field-label is-normal">
                    <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                </div>
                <div class="field-body">
                    <div class="field">
                        <div class="control">
                            {% if field.field.widget.input_type == "text" %}
                            {% render_field field class="input" placeholder=field.label %}
                            {% else %}
                            {% render_field field class="textarea" placeholder=field.label %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="field is-horizontal">
                <div class="field-label">
                    <!-- Left empty for spacing -->
                </div>
                <div class="field-body">
                    <div class="field">
                        <div class="control">
                            <input type="submit" value="Add" class="button is-primary is-large is-fullwidth">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
{% comment %} Add Offline memeber form section {% endcomment %}
<section class="section" id="offline-member-section">
    <div class="box">
        <h1 class="title has-text-centered">Offline members for today</h1>
        <section class="section">
            <h2 class="subtitle has-text-centered">Add offline member</h2>
            <form action="{% url 'add_offline_member' %}" method="post">
                {% csrf_token %}
                <div class="columns">
                    <div class="column is-offset-2">
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label for="{{ offline_members_form.name.id_for_label }}" class="label">Developer/Tester
                                    Name</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <p class="control">
                                        {% render_field offline_members_form.name class="input is-primary" placeholder=offline_members_form.name.label %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label for="{{ offline_members_form.role.id_for_label }}" class="label">Role</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <div class="select is-primary">
                                            {{ offline_members_form.role }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="field is-horizontal">
                            <div class="field-label">
                                <!-- Left empty for spacing -->
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <input type="submit" value="Add" class="button is-primary">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </section>
        <h2 class="subtitle has-text-centered">Offline members</h2>
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>
                        Developer/Tester
                    </th>
                    <th>
                        Role
                    </th>
                    <th>
                        Delete
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for member in offline_members %}
                <tr>
                    <td>
                        {{ member.name }}
                    </td>
                    <td>
                        {{ member.get_role_display }}
                    </td>
                    <td>
                        <a href="{% url 'delete_offline_member' member.id%}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% comment %} Generate email controls section {% endcomment %}
<section class="section" id="generate-email-controls">
    <div class="box">
        <h1 class="title has-text-centered">Generate email</h1>
        <div class="columns is-centered">
            <div class="column is-one-fifth">
                <a class="button is-link" href="{% url 'create_email_within_browser' %}">Create email within
                    browser</a>
            </div>
            <div class="column is-one-fifth">
                <a class="button is-danger" href="{% url 'create_email_in_outlook' %}">Create email in outlook</a>
                <p class="help is-danger">Please don't click on this unless you are hosting this app.</p>
            </div>
        </div>
    </div>
</section>
{% endblock content %}